name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: jeromep01/OopWinformsDesigner.git
          path: main   
        
#      - name: Setup NuGet.exe
#        uses: nuget/setup-nuget@v1
#        with:
#          nuget-version: latest
#      - run: nuget restore

      - name: Build
        run: |
           cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe $Env:GITHUB_WORKSPACE\
           
      - uses: actions/upload-artifact@v1
        with:
          name: artifact
          path: ./OopWinformsDesigner/bin/Debug
